### ISSUE TITLE
Sync data transfer 

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#108]
Feature agera-edc/MinimumViableDataspace#30
After agera-edc/DataSpaceConnector#228 

## Description

As a dataspace participant I want to initiate a contract negotiation with another participant and perform data transfer as a synchronous operation.

## Acceptance Criteria

(Need to discuss with Jim/Paul and add more details)

**Comment by zeier** [comment]
Not planned to cover this item by the Agera crew until end of August.
