### ISSUE TITLE
Transfer remains in IN_PROGRESS state in provider transfer history

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#136]
## Description
In MVD ui tranfer remains in IN_PROGRESS state even after its completion if check provider connector transfer history UI page.
On consumer side it shows COMPLETED.

## Expected Behavior
Completed transfer must show COMPLETED state in both consumer and provider transfer history page.

## Current Behavior 

Provider
<img width="784" alt="image" src="https://user-images.githubusercontent.com/555114/167849613-cfe96c34-0924-4988-b17b-eb4e021f30c4.png">

Consumer
<img width="776" alt="image" src="https://user-images.githubusercontent.com/555114/167849737-5e4ddbad-b35c-4119-9272-ebddb3b30128.png">

**Comment by algattik** [comment]
This is not an MVD bug, but by design in EDC.
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/9436ebff2ba194c67ed4fc1f4dd0b98a07b3cf19/core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java#L332

**Comment by algattik** [comment]
Pending decision in upstream issue

**Comment by zeier** [comment]
Closing as we won't be further tracking the issue, since it will be tracked upstream in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1287
