### ISSUE TITLE
Upload gatling report in MVD CD

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#149]
## Description

Gatling reports for system tests are not available yet for the MVD.

Gatling reports are helpful to investigate why system-tests are failing in the CD pipeline, because it is easier to understand where the system-test fails by looking at the Gatling report compared to other means of investigation.

## Acceptance Criteria

- [ ] Gatling reports for MVD system tests are available

## Tasks

- [ ] Upload gatling report in MVD CD of system-tests

**Comment by cpeeyush** [comment]
Initial draft  PR : https://github.com/agera-edc/MinimumViableDataspace/pull/173

**Comment by zeier** [comment]
Duplicate, merging with #172
