### ISSUE TITLE
Destroy workflow can be green if a called workflow fails

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#151]
# Description
Destroy workflow can be green if a called workflow fails

Destroy worklow look green when it fails. For example see screenshot:

<img width="1204" alt="Screenshot 2022-05-17 at 11 26 56" src="https://user-images.githubusercontent.com/17216799/168884992-1215b9ac-bdf2-40e4-ab4b-b565e0feef89.png">

**Comment by cpeeyush** [comment]
Found this https://github.community/t/continue-on-error-allow-failure-ui-indication/16773, Not sure if this something currently supported.
