### ISSUE TITLE
Naming Conventions for Azure Resources

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#152]
## Description

The user-provided prefix when running the Deploy action us used to as part of the name for the Azure resources to be created, and thus needs to adhere to the corresponding naming conventions (and restrictions).

For example, the Deploy action will fail if a dash is provided as part of the prefix.

Issues encountered during the GAIA-X hackathon:
- The prefix one of the hackathon participant provided during running a deploy workflow was too long and also had a underscore.
- Other time one of the hackathon participant put underscore in terraform storage account name (GitHub secret) and had an issue during initial deployment workflow.

The goal of this story is to improve our [documentation](https://github.com/agera-edc/MinimumViableDataspace/blob/main/docs/developer/continuous_deployment.md) to make naming conventions more explicit.

## Acceptance Criteria

- [ ] [continuous deployment docs](https://github.com/agera-edc/MinimumViableDataspace/blob/main/docs/developer/continuous_deployment.md) contain information about naming conventions
- [ ] The description for the prefix when running the Deploy action should contain a hint that only lowercase letters and numbers can be used
- [ ] The deployment pipeline detects invalid prefixes and stops early in case of invalid prefixes

**Comment by algattik** [comment]
@zeier should the pipeline detect this and stop early?

**Comment by zeier** [comment]
@algattik If we can detect this and stop the pipeline early with low implementation effort that would be ideal, because it would prevent to have a wait time until the person that triggered the pipeline notices that something went wrong. It's a nice to have though.

**Comment by algattik** [comment]
a one-liner like this should do the job

```
- run: [[ "$RESOURCES_PREFIX" =~ ^[a-z][a-z0-9]{0,6}$ ]]
```
