### ISSUE TITLE
Deleted assets still visible in catalog

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/MinimumViableDataspace#156]
## Description

If we delete a contract definition/offer and/or related asset also. Still, it is visible under catalog of other participants. 

May have been fixed today under PR https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1498 , upstream issue https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1495

## Expected Behavior

If a dataspace participant remove a contract definition and assets it should be removed from federated catalog as well and no more should be available for negotiations/transfer.

**Comment by zeier** [comment]
If the issue is not fixed with the current EDC version, suggestion is to get in touch with Paul, as he is working on this topic.

**Comment by bscholtes1A** [comment]
Normally this should be fixed with recent versions of the EDC

**Comment by algattik** [comment]
Verified that the bug is not extant.

- Deployed MVD
- Ensured asset from company3 is visible in company2 catalog
- Deleted contract definition and asset in company3 (via Web UI)
- Refreshed company2 catalog web view
- Asset from company3 is not visible anymore
