### ISSUE TITLE
DID Documents: Link to Self-Description

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#187]
Feature #36 
After #19, #186

## Description

Each DID document should contain the link to the corresponding self-description.

A dataspace participant is identified via its DID document, which serves as the root from which additional information about a participant, like the self-description, can be retrieved.

## Acceptance Criteria

- [ ]  DID documents (dataspace participants including dataspace authority) contain the link to the corresponding self-description.

## Tasks
- [ ] Add endpoint to serve self-description endpoint.
- [ ] Test coverage.

**Comment by bscholtes1A** [comment]
Is this still needed?

In https://github.com/eclipse-dataspaceconnector/IdentityHub/pull/23 we introduced the Identity Hub endpoint serving the self-description. 

This GET endpoint has URL: `IDENTITY_HUB_BASE_URL + /self-description`, while IDENTITY_HUB_BASE_URL is already provided as a `serviceEndpoint` in the DID document. 

So as long as, each DID document contains the URL of the identity hub, then it also indirectly contains the URL of the self-description endpoint.

**Comment by marcgs** [comment]
@bscholtes1A I think this is indeed required for correctness, as it is not mandatory that the self-description document is served by the Identity Hub.
