### ISSUE TITLE
MVD & UI - UI Catalog is randomly empty

### ISSUE THREAD

**Issue by ouphi** [agera-edc/MinimumViableDataspace#193]
## Description
When deploying MVD, and looking at the UI of one participant, the catalog is randomly empty or contains items (not always the same items).

This could be a bug in the crawler or the EDCDataDashboard. The origin of the bug is not clear.

**Comment by bscholtes1A** [comment]
Normally this has been fixed by https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1498

**Comment by cpeeyush** [comment]
Upstream bug issue (maybe related) https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1703

**Comment by zeier** [comment]
@paullatzelsperger will coordinate with @bscholtes1A to get https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1703 resolved.

**Comment by zeier** [comment]
Upstream EDC bug is fixed, latest EDC version needs to be integrated and tested in the MVD. Removing `blocked` tag.

**Comment by zeier** [comment]
While the upstream issue is fixed now, the issue still persists. There are most likely multiple issues, https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1703 being one of them, but not the only one.
