### ISSUE TITLE
Registration Service - Identity Hub, Policies and Verifiable Credentials

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#24]
After agera-edc/MinimumViableDataspaceFork#58 agera-edc/MinimumViableDataspaceFork#71 

## Description

This feature covers registration service next steps in terms of interacting with identity hub, applying enrollment policies and verifying Verifiable Credentials signatures.

## Acceptance Criteria

- [x] Able to verify participant JWS
- [x] Issues a dataspace membership VC and pushes it to the corresponding identity hub
- [x] Obtains participant verifiable credentials
- [x] Apply required policies on obtained participant verifiable credentials
- [x] Accepts only verifiable credentials signed by a trusted party (GAIA-X)

## Stories

- [x] #14
- [x] #13
- [x] #225
- [x] #12
- [x] #11
- [ ] ~#10~ currently the policy engine in EDC does not support combining conditions (gaiaxMember=true AND vcIssuer=gaiax)
- [ ] ~Identity hub token authentication: Registration service client app sends a time-limited bearer token, allowing registration service to request verifiable credentials from caller's identity hub~ -> Identity Hub authentication out scoped for simplicity
- [x] #174

**Comment by marcgs** [comment]
Suggestion to document verification of the self-description document against the GAIA-X service during the onboarding flow

**Comment by marcgs** [comment]
Moving #10 out of this feature, as currently the policy engine in EDC does not support combining conditions (gaiaxMember=true AND vcIssuer=gaiax).
