### ISSUE TITLE
Decentralized Identifiers

### ISSUE THREAD

**Issue by chrislomonico** [agera-edc/MinimumViableDataspace#28]
## Description

[Draft Based on Team Discussions]

## Acceptance Criteria
 
- [ ] IDS requests are secured using Wed DID
- [ ] JWTs are verified using the DID of the requestor
- [ ] Sample mocked Verifiable Credentials are in place (region=eu) and enforced at each connector

## Stories

- [x] #31
- [x] #43
- [x] #34
- [x] #5 
- [x] #35
- ~[ ] #61 (stretch goal)~

**Comment by marcgs** [comment]
> > It is questionable if the IdentityHub deployment is required for this feature. EDC contains a `DummyCredentialsVerifier` that can be used to mock credential retrieval which seems perfectly fine for this step. Calling the IdentityHub in a similar manner like `IdentityHubCredentialsVerifier` does (see [eclipse-dataspaceconnector/DataSpaceConnector#1070](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1070)) will return empty credentials unless we seed data as well. To me this area is still too unclear and it is worth keeping it simple at the beginning. @algattik
> 
> Removing IdentityHub integration for this feature. The Verifiable Credentials provided by the Hub bring no value without a policies and a policy enforcement mechanism in place. This should be reevaluated together once there is more clarity. @zeier

As discussed in the planning, evaluation of a basic policy "data resides in EU" should work. Adding stories for IdentityHub.
