### ISSUE TITLE
MVD local machine setup for EDC users

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#54]
Feature #53 
After #20

## Description
Enable MVD to run on local computers EDC users for educational purposes. One should be able to understand the relevant components and steps required to set up the MVD, and play around with these in their own setup

## Acceptance Criteria
- [ ] Simplified setup for non-technical EDC users allowing to experiment with MVD on a local machine
- [ ] Enhance documentation to enable understanding of MVD components and their interactions

## Tasks

**Comment by zeier** [comment]
Discarding this story as running a local MVD instance for EDC users is (in contrast to local setup for developers) is not a use case we currently want to cover.
