### ISSUE TITLE
JWT Hardening

### ISSUE THREAD

**Issue by marcgs** [agera-edc/MinimumViableDataspace#61]
Feature #28 
After #19 
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1176

## Description
JWTs are used in EDC as means to authenticate IDS requests. The current implementation allows for a malicious entity that gets ahold of a JWT to impersonate the original sender, and thus send requests to any other participant.

Use the [audience](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3) claim to identify the JWT target. A JWT token sent to another participant than the one it was initially intended for will be rejected. This prevents from a malicious participant to reuse JWTs sent to him as a producer, to impersonate the signer of that JWT  as a consumer himself.

The DID of the messages receiver must be used as value of the audience claim. These should be available in the registry which needs to be extended to keep track of the DIDs for each participant.

## Acceptance Criteria
- [ ] Extend the registry json to contain the DID for each participant
- [ ] Extend EDC to fill the JWT audience claim using the message receiver DID (see [prototype code](https://github.com/agera-edc/DataSpaceConnector/pull/222/files))
- [ ] Extend EDC to verify audience claim on each IDS message receival (see [prototype code](https://github.com/agera-edc/DataSpaceConnector/pull/222/files))
- [ ] Integration tests to check audience verification is working properly

**Comment by algattik** [comment]
@marcgs why use the target DID as audience? Using the target URL seems simpler as the client connector has it as a matter of course, and the target connector also knows it in its `IDS_WEBHOOK_ADDRESS`.

The audience is often a URL in other systems (e.g. from Azure AD: `  "aud": "https://management.core.windows.net/"`)

**Comment by algattik** [comment]
Blocked until upstream issues in EDC are resolved.

**Comment by zeier** [comment]
Removed from our scope, we will keep the upstream issue to address the topic.
