### ISSUE TITLE
Signed Verifiable Credentials

### ISSUE THREAD

**Issue by zeier** [agera-edc/MinimumViableDataspace#78]
## Description

[Verifiable credentials](https://www.w3.org/TR/vc-data-model/#credentials) are tamper-proof credentials that can be verified cryptographically. A [credential](https://www.w3.org/TR/vc-data-model/#dfn-credential) is a set of one or more [claims](https://www.w3.org/TR/vc-data-model/#dfn-claims) made by the same [entity](https://www.w3.org/TR/vc-data-model/#dfn-entities) (in our case the dataspace participant or the dataspace authority). The IdentityHub is the component that delivers verifiable credentials for a dataspace participant. In the MVD, each participant has an own IdentityHub where its verifiable credentials are stored.

In a dataspace, a participant might present claims signed by different authorities. For example, the claim that a participant is a member of a given dataspace is signed by the dataspace authority, whereas a claim that a participant holds a specific ISO certification is signed by a corresponding certification body.

The dataspace authority is the trust anchor for the MVD. A GAIA-X membership Verifiable Credential signed by external trusted authority (exemplary deployment of a GAIA-X authority with private key and a DID document containing a public key) will be a precondition verified by the dataspace authority for joining the dataspace. Once a participant is accepted into the MVD, a separate dataspace membership Verifiable Credential must be issued for the participant by the dataspace authority.

We will use [JSON Web Key](https://www.rfc-editor.org/rfc/rfc7517#section-4) format with [Elliptic Curve](https://en.wikipedia.org/wiki/Elliptic-curve_cryptography) as we will reuse the [EDC libraries to manage the decentralised identity](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/iam/decentralized-identity).
 
## Acceptance Criteria

- [ ] Infrastructure to issue and validate verifiable credentials is available
- [ ] Certificate infrastructure to be used in MVD is defined and documented in an ADR
- [ ] GAIA-X membership Verifiable Credential can be issued by an external authority trusted by dataspace participants and can be verified by the dataspace authority
- [ ] MVD Membership verifiable credentials signed by the dataspace authority can be issued and verified by any dataspace participant
- [ ] Documentation (ADRs) on how verifiable credentials incl. certificate infrastructure are handled for the MVD

## Stories

- [x] #18
- [x] #17
- [x] #151

**Comment by zeier** [comment]
Clarified that we will use the region for catalog filtering, and a GAIA-X membership VC to join the dataspace.

**Comment by Izzzu** [comment]
As decided during the design session I changed the description from: 
_We will use [X.509](https://en.wikipedia.org/wiki/X.509) certificates (any PKI could be used, X.509 was chosen because of its broad usage)._
to
_We will use [JSON Web Key](https://www.rfc-editor.org/rfc/rfc7517#section-4) format with [Elliptic Curve](https://en.wikipedia.org/wiki/Elliptic-curve_cryptography) as we will reuse the EDC libraries to manage the decentralised identity_.
