### ISSUE TITLE
View Assets to Share with Others

### ISSUE THREAD

**Issue by algattik** [agera-edc/MinimumViableDataspace#86]
Feature #3 

## Description

As a dataspace participant I want to look at all the data assets I manage, and (potentially, if included in contract definitions) offer to share with other participants.

Out of scope:
- deleting assets
- editing assets

## Acceptance Criteria
- [ ] Web UI lists all assets and allows sorting, filtering and grouping (by name, asset owner, etc.) 
- [ ] Assets include all data assets I own.
- [ ] Documentation on how to view offerings through the UI is available
- [ ] Assets can be viewed based on step by step instructions without having deep technical expertise

**Comment by zeier** [comment]
Current capabilities are sufficient, removing this story from scope.
