### ISSUE TITLE
Search Dataspace Catalog

### ISSUE THREAD

**Issue by algattik** [agera-edc/MinimumViableDataspace#87]
Feature #3 
After #10 

## Description

As a dataspace participant I want to be able to locate the contract offer I need, among all the data assets that other participants offer to share with me.

The connector's web UI offers a page to display all data offerings (#10).

## Acceptance Criteria
- [ ] Web UI allows sorting, filtering and grouping (by name, asset owner, etc.) 
- [ ] Documentation on how to search offerings through the UI is available
- [ ] Offerings can be searched based on step by step instructions without having deep technical expertise

**Comment by zeier** [comment]
Current capabilities are sufficient, removing this story from scope.
